### ISSUE TITLE
Import Animations from ovos-plugin-manager

### ISSUE THREAD

**Issue by NeonDaniel** [OpenVoiceOS/ovos-PHAL-plugin-dotstar#1]
The [`Animation` class](https://github.com/OpenVoiceOS/ovos-PHAL-plugin-dotstar/blob/dev/ovos_PHAL_plugin_dotstar/light_patterns.py#L14) is re-defined from [ovos-plugin-manager](https://github.com/OpenVoiceOS/ovos-plugin-manager/blob/dev/ovos_plugin_manager/hardware/led/animations.py). Can OPM be updated to support this plugin too instead of duplicating code?

**Comment by builderjer** [comment]
It was discussed at first, and that is the code I was using. @JarbasAl would like the hardware section of OPM to be depreciated

**Comment by builderjer** [comment]
I am choosing to use `Color` from `ovos-lingua-franca` so the animations do not work here.

https://github.com/OpenVoiceOS/ovos-plugin-manager/issues/228#issuecomment-2133428559
